dist: trusty
sudo: required
notifications:
  email: false
language: python
cache: pip
python:
  {% if cookiecutter.supports_py2 == 'y' -%}
  - "2.7"
  - "pypy"
  {%- endif %}
  {% if cookiecutter.supports_py3 == 'y' -%}
  - "3.5"
  {%- endif %}
env:
  global:
    - CATMAID_DIR=$TRAVIS_BUILD_DIR/travis/CATMAID
addons:
  apt:
    sources:
    - precise-pgdg-9.5
    packages:
    - postgresql-9.5
    - postgresql-contrib-9.5
  postgresql: 9.5
before_install:
  - travis_retry sudo apt-get update -qq
  # setup CATMAID
  - git clone https://github.com/catmaid/CATMAID.git $CATMAID_DIR
  - cd $CATMAID_DIR
  - ./scripts/travis/install_requirements.sh
  - ./scripts/travis/setup_database.sh
  - ./scripts/travis/configure_catmaid.sh
  - pip install coveralls
install:
  - pip install -e $TRAVIS_BUILD_DIR
  - cd $CATMAID_DIR/django/projects
  - python manage.py migrate --noinput
  - python manage.py collectstatic --link --noinput
script:
  - coverage run --source={{ cookiecutter.app_name }} manage.py test {{ cookiecutter.app_name }}.tests
after_success:
  - coveralls
