dist: trusty
sudo: required
language: python
cache: pip
python:
  {% if cookiecutter.supports_py2 == 'y' -%}
  - "2.7"
  - "pypy"
  {%- endif %}
  {% if cookiecutter.supports_py3 == 'y' -%}
  - "3.5"
  - "3.6"
  - "pypy3"
  {%- endif %}
env:
  - CATMAID_DIR=$TRAVIS_BUILD_DIR/travis/CATMAID CATMAID_BRANCH=master
  - CATMAID_DIR=$TRAVIS_BUILD_DIR/travis/CATMAID CATMAID_BRANCH=dev
matrix:
  fast_finish: true
  allow_failures:
    - env: CATMAID_DIR=$TRAVIS_BUILD_DIR/travis/CATMAID CATMAID_BRANCH=dev
addons:
  apt:
    sources:
    - precise-pgdg-9.6
    packages:
    - postgresql-9.6
    - postgresql-contrib-9.6
  postgresql: 9.6
before_install:
  - travis_retry sudo apt-get update -qq
  # setup CATMAID
  - git clone -b $CATMAID_BRANCH https://github.com/catmaid/CATMAID.git $CATMAID_DIR
  - cd $CATMAID_DIR
  - ./scripts/travis/install_requirements.sh
  - ./scripts/travis/setup_database.sh
  - ./scripts/travis/configure_catmaid.sh
  - pip install coveralls
install:
  - pip install -e $TRAVIS_BUILD_DIR
  - cd $CATMAID_DIR/django/projects
  - python manage.py migrate --noinput
  - python manage.py collectstatic --link --noinput
script:
  - coverage run --source={{ cookiecutter.app_name }} manage.py test {{ cookiecutter.app_name }}.tests
after_success:
  - coveralls

