language: python
python:
  - 3.7
  - 3.6
  - 3.5

before_install:
  - pip install cookiecutter flake8
  - npm install jshint
  - export PATH=$(npm bin):$PATH

script:
  - cd example
  - ./regenerate.sh
  - cd CATMAID-myextension
  - flake8 --config .travis.flake8 --ignore=F401 .
  - jshint --config .travis.jshintrc .
